### ISSUE TITLE
ERROR: NO COMMON CONTIGS FOUND BETWEEN THE BAM FILE AND THE FASTA FILE

### ISSUE THREAD

**Issue by bo8883** [fenderglass/hapdup#18]
I followed the directions exactly but I get this error.  Do you know what's going wrong?  Thanks.

bash-4.2$ singularity exec --bind $HD_DIR hapdup_0.6.sif hapdup --assembly $HD_DIR/assembly.fasta --bam $HD_DIR/lr_mapping.bam --out-dir $HD_DIR/hapdup -t 64 --rtype ont
INFO:    Converting SIF file to temporary sandbox...
[2022-06-23 13:01:10] INFO: Skipped filtering phase
[2022-06-23 13:01:10] INFO: Running: pepper_variant call_variant -b /home/bozhou/src/hapdup/filtered.bam -f /home/bozhou/src/assembly.fasta -o /home/bozhou/src/hapdup/pepper -m /home/bozhou/src/hapdup/pepper/pepper_model.bin -t 64 -s Sample --ont_r9_guppy5_sup --include-supplementary --no_quantized 2>&1 |tee /home/bozhou/src/hapdup/pepper/pepper.log
[06-23-2022 13:01:11] INFO: ONT VARIANT CALLING MODE SELECTED.
[06-23-2022 13:01:11] INFO: MODE: PEPPER SNP
[06-23-2022 13:01:11] INFO: THRESHOLDS ARE SET TO:
[06-23-2022 13:01:11] INFO: MIN MAPQ:				5
[06-23-2022 13:01:11] INFO: MIN SNP BASEQ:			1
[06-23-2022 13:01:11] INFO: MIN INDEL BASEQ:			1
[06-23-2022 13:01:11] INFO: MIN SNP FREQUENCY:			0.1
[06-23-2022 13:01:11] INFO: MIN INSERT FREQUENCY:		0.15
[06-23-2022 13:01:11] INFO: MIN DELETE FREQUENCY:		0.15
[06-23-2022 13:01:11] INFO: MIN COVERAGE THRESHOLD:		3
[06-23-2022 13:01:11] INFO: MIN CANDIDATE SUPPORT:		2
[06-23-2022 13:01:11] INFO: MIN SNP CANDIDATE FREQUENCY:	0.1
[06-23-2022 13:01:11] INFO: MIN INDEL CANDIDATE FREQUENCY:	0.1
[06-23-2022 13:01:11] INFO: SKIP INDEL CANDIDATES:		False
[06-23-2022 13:01:11] INFO: MAX ALLOWED CANDIDATE IN ONE SITE:	4
[06-23-2022 13:01:11] INFO: MIN SNP PREDICTIVE VALUE:		0.1
[06-23-2022 13:01:11] INFO: MIN INSERT PREDICTIVE VALUE:	0.25
[06-23-2022 13:01:11] INFO: MIN DELETE PREDICTIVE VALUE:	0.25
[06-23-2022 13:01:11] INFO: SNP QV CUTOFF FOR RE-GENOTYPING:	15
[06-23-2022 13:01:11] INFO: INDEL QV CUTOFF FOR RE-GENOTYPING:	10
[06-23-2022 13:01:11] INFO: REPORT ALL SNPs ABOVE THRESHOLD:	0
[06-23-2022 13:01:11] INFO: REPORT ALL INDELs ABOVE THRESHOLD:	0
[06-23-2022 13:01:11] INFO: CALL VARIANT MODULE SELECTED
[06-23-2022 13:01:11] INFO: RUN-ID: 06232022_130111
[06-23-2022 13:01:11] INFO: IMAGE OUTPUT: /home/bozhou/src/hapdup/pepper/images_06232022_130111/
[06-23-2022 13:01:11] INFO: STEP 1/3 GENERATING IMAGES:
[06-23-2022 13:01:11] ERROR: NO COMMON CONTIGS FOUND BETWEEN THE BAM FILE AND THE FASTA FILE.rm: cannot remove '/home/bozhou/src/hapdup/pepper/images*': No such file or directory
rm: cannot remove '/home/bozhou/src/hapdup/pepper/predictions*': No such file or directory
[2022-06-23 13:01:11] ERROR: Missing output: /home/bozhou/src/hapdup/pepper/PEPPER_VARIANT_FULL.vcf
Traceback (most recent call last):
  File "/usr/local/bin/hapdup", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/hapdup/main.py", line 183, in main
    file_check(pepper_vcf)
  File "/usr/local/lib/python3.8/dist-packages/hapdup/main.py", line 110, in file_check
    raise Exception("Missing output")
Exception: Missing output
INFO:    Cleaning up image...

**Comment by bo8883** [comment]
okay, I figured it out; need to remove the filtered.bam file

**Comment by Axze-rgb** [comment]
Hello, I am having the same issue and I don't understand the solution. Should I remove the filter bam and relaunch HapDup at another point in the pipeline? How do I do that? 
Thanks

**Comment by bo8883** [comment]
If I remember correctly, there was already a filter.bam file in the directory, and that needs to be removed before restarting. Sorry, I could be wrong, but it's been a while.

**Comment by Axze-rgb** [comment]
No worries I restarted everything from the mapping of long reads on the assembly and it worked. It doesn't make any sense but I got my phased assembly.
